  hello_moveit:
    ros__parameters:
      h: &h 0.1  #hitri hodi
      p: &p 0.005  #počasni hodi
      a: &a 0.1

      targets:
        - 1.0
        - 0.0
        - 1.15
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0
        
        - 0.928940      #x
        - -0.012286     #y
        - 0.7           #z
        - 0.0           #roll
        - 0.0           #pitch
        - 0.0           #yaw
        - *h           #velocity_scaling
        - *a           #acceleration_scaling
        - 0.0           #delay_seconds
        - 0.0           #vakuum

        - 0.928940
        - -0.012286
        - 0.643352
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 1.5
        - 1.0

        - 0.928940
        - -0.012286
        - 0.7
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 0.0
        - 0.0

        - 0.857725
        - 0.568476
        - 0.85
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0

        - 0.857725
        - 0.568476
        - 0.786884
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 1.5
        - 2.0

        - 0.857725
        - 0.568476
        - 0.85
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 0.0
        - 0.0

        - 1.0
        - 0.0
        - 1.15
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0

