  hello_moveit:
    ros__parameters:
      h: &h 0.2  #hitri hodi
      p: &p 0.05  #počasni hodi
      a: &a 0.05

      targets:
        - 1.0
        - 0.0
        - 1.15
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0
        
        - 0.928940      #x
        - -0.015914     #y
        - 0.8           #z
        - 0.0           #roll
        - 0.0           #pitch
        - 0.0           #yaw
        - *h           #velocity_scaling
        - *a           #acceleration_scaling
        - 0.0           #delay_seconds
        - 0.0           #vakuum

        - 0.928940
        - -0.015914
        - 0.745608
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 3.0
        - 1.0

        - 0.928940
        - -0.015914
        - 0.8
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 0.0
        - 0.0

        - 0.857725
        - 0.568476
        - 0.95
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0

        - 0.857725
        - 0.568476
        - 0.888854
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 3.0
        - 2.0

        - 0.857725
        - 0.568476
        - 0.95
        - 0.0
        - 0.0
        - 0.0
        - *p
        - *a
        - 0.0
        - 0.0

        - 1.0
        - 0.0
        - 1.15
        - 0.0
        - 0.0
        - 0.0
        - *h
        - *a
        - 0.0
        - 0.0

