# SPDX-FileCopyrightText: 2025, FANUC America Corporation
# SPDX-FileCopyrightText: 2025, FANUC CORPORATION
#
# SPDX-License-Identifier: Apache-2.0

# Supported types:
#  GO
IOType io_type
uint16 index
uint16 value
---
int32 result
